set number
filetype plugin indent on
syntax on
set backspace=indent,eol,start
set nocompatible
set laststatus=2

"" use markdown for vimwiki
let g:vimwiki_list = [{'path': '~/vimwiki/',
                       \ 'syntax': 'markdown', 'ext': '.md'}]
"" integrate Goyo and Limelight
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!

"" specify limelight color
let g:limelight_conceal_ctermfg = 'darkgray'
